name: Format Code

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install

      - run: npm run format:check
