name: Create build for release

on: push

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Set up npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Setup Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install

      - name: Build and Convert the release macOS version
        run: |
          npm run build
          cd dist
          zip -r build.zip safari
          xcrun safari-web-extension-converter safari
          xcodebuild -project /Users/runner/work/prettierlichess/prettierlichess/dist/Prettier\ Lichess/Prettier\ Lichess.xcodeproj -target "Prettier Lichess (macOS)" build

      

      - name: Upload Safari macOS app file
        uses: actions/upload-artifact@v3
        with:
          name: build-version
          path: /Users/runner/work/prettierlichess/prettierlichess/dist/Prettier\ Lichess/build/Release/Prettier\ Lichess.app
