name: Run web-ext lint

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  lint-source:
    name: Lint source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Setup Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install

      - name: Run web-ext lint
        run: |
          cd ./src/
          npm install --global web-ext
          web-ext lint

  lint-build:
    name: Lint build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Setup Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install

      - run: npm run build

      - name: Run web-ext lint
        run: |
          cd ./dist/
          npm install --global web-ext
          web-ext lint
